In [1]:
import pandas as pd
import numpy as np

We train the `log_quadratic` model on the historical training dataset.

In [2]:
df_train = pd.read_parquet("output/historical_data/train/lev_sigma<0.6_std.parquet")

In [3]:
print("min vol", df_train["realized_vol"].min())
print("max vol", df_train["realized_vol"].max())

min vol 0.03185918243743643
max vol 0.5999720507676751

In [4]:
bins = np.linspace(df_train["realized_vol"].min(), df_train["realized_vol"].max(), 200)

df_train["realized_vol"] = pd.cut(x=df_train["realized_vol"], bins=bins)

In [5]:
df_train["realized_vol"] = df_train["realized_vol"].apply(lambda x: x.mid)

In [ ]:
grouped_df_train = df_train.groupby(by=["leverage_factor", "realized_vol"])[
    ["PnL"]
].std()

/tmp/ipykernel_25314/3578563250.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_df_train = df_train.groupby(by=["leverage_factor", "realized_vol"])[["PnL"]].std()

In [7]:
grouped_df_train.reset_index(inplace=True)

In [8]:
grouped_df_train.rename(columns={"PnL": "PnL_std"}, inplace=True)

In [9]:
grouped_df_train

Ticker  leverage_factor realized_vol   PnL_std
0                  1.01      0.03330  0.000003
1                  1.01      0.03615  0.000029
2                  1.01      0.03900  0.000065
3                  1.01      0.04185  0.000084
4                  1.01      0.04470  0.000100
...                 ...          ...       ...
19895              3.00      0.58750  0.186795
19896              3.00      0.59000  0.146202
19897              3.00      0.59250  0.128614
19898              3.00      0.59550  0.146250
19899              3.00      0.59850  0.155109

[19900 rows x 3 columns]

In [ ]:
import models

model = models.generate_model(degree=2, take_log=True)
model.fit(
    grouped_df_train[["leverage_factor", "realized_vol"]], grouped_df_train["PnL_std"]
)

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('log_linear',
                 TransformedTargetRegressor(func=<ufunc 'log1p'>,
                                            inverse_func=<ufunc 'expm1'>,
                                            regressor=LinearRegression(fit_intercept=False)))])

Test

In [ ]:
from sklearn.metrics import mean_squared_error as mse

df_test = pd.read_parquet("output/historical_data/train/lev_sigma<0.6_std.parquet")
df_test["realized_vol"] = pd.cut(x=df_test["realized_vol"], bins=bins).apply(
    lambda x: x.mid
)

grouped_df_test = df_test.groupby(by=["leverage_factor", "realized_vol"])[["PnL"]].std()
grouped_df_test.reset_index(inplace=True)
grouped_df_test.rename(columns={"PnL": "PnL_std"}, inplace=True)

grouped_df_test

/tmp/ipykernel_25314/4151807085.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_df_test = df_test.groupby(by=["leverage_factor", "realized_vol"])[["PnL"]].std()

Ticker  leverage_factor realized_vol   PnL_std
0                  1.01      0.03330  0.000003
1                  1.01      0.03615  0.000029
2                  1.01      0.03900  0.000065
3                  1.01      0.04185  0.000084
4                  1.01      0.04470  0.000100
...                 ...          ...       ...
19895              3.00      0.58750  0.186795
19896              3.00      0.59000  0.146202
19897              3.00      0.59250  0.128614
19898              3.00      0.59550  0.146250
19899              3.00      0.59850  0.155109

[19900 rows x 3 columns]

In [ ]:
pred = model.predict(grouped_df_test[["leverage_factor", "realized_vol"]])

print("mse =", mse(grouped_df_test["PnL_std"], pred))
print(
    "R2  =",
    model.score(
        grouped_df_test[["leverage_factor", "realized_vol"]], grouped_df_test["PnL_std"]
    ),
)

mse = 0.00023794036830907588
R2  = 0.8637408476355051